library(DiffBind)
x = read.table("DiffBind-B73-Cold.txt",sep='\t',head=T)
tamoxifen <- dba(sampleSheet=x)
tamoxifen <- dba.count(tamoxifen)
tamoxifen1 <- dba.contrast(tamoxifen, categories=DBA_CONDITION, minMembers=2)
tamoxifen2 <- dba.analyze(tamoxifen1)
tamoxifen.DB <- dba.report(tamoxifen2)
write.table(tamoxifen.DB, file="test.txt")